version: '3.8'

services:
  db:
    image: postgres:15
    container_name: myapp_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: confirmado
      POSTGRES_DB: backend_api_development
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    container_name: backend_api
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgres://user:password@db:5432/myapp_development
    command: ["bash", "-c", "rm -f tmp/pids/server.pid && rails server -b 0.0.0.0"]

volumes:
  pgdata:
